#!/usr/bin/env python3

import json
import os
import urllib.request
from collections import defaultdict
from pathlib import Path
from xml.sax.saxutils import escape

USERNAME = os.environ.get("PROFILE_USERNAME", "atlasru")
TOKEN = os.environ.get("GITHUB_TOKEN", "")
OUT = Path("assets")
OUT.mkdir(exist_ok=True)

HEADERS = {
    "Accept": "application/vnd.github+json",
    "User-Agent": "atlasru-profile-stats",
    "X-GitHub-Api-Version": "2022-11-28",
}
if TOKEN:
    HEADERS["Authorization"] = f"Bearer {TOKEN}"


def api(url):
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode("utf-8"))


def get_repos():
    repos = []
    page = 1
    while True:
        batch = api(
            f"https://api.github.com/users/{USERNAME}/repos"
            f"?per_page=100&page={page}&sort=updated&type=owner"
        )
        if not batch:
            break
        repos.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return [r for r in repos if not r.get("fork")]


def fmt(n):
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}m"
    if n >= 1_000:
        return f"{n / 1_000:.1f}k"
    return str(n)


def svg_shell(width, height, body):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
<style>
  .bg {{ fill:#0d1117; }}
  .border {{ fill:none; stroke:#30363d; stroke-width:1; }}
  .title {{ fill:#ff3030; font:600 16px ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace; }}
  .label {{ fill:#8b949e; font:12px ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace; }}
  .value {{ fill:#e6edf3; font:600 20px ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace; }}
  .small {{ fill:#c9d1d9; font:12px ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace; }}
</style>
<rect class="bg" x="0.5" y="0.5" width="{width-1}" height="{height-1}" rx="8"/>
<rect class="border" x="0.5" y="0.5" width="{width-1}" height="{height-1}" rx="8"/>
{body}
</svg>'''


def build_stats(user, repos):
    stars = sum(r.get("stargazers_count", 0) for r in repos)
    forks = sum(r.get("forks_count", 0) for r in repos)
    size_kb = sum(r.get("size", 0) for r in repos)

    rows = [
        ("public repos", len(repos)),
        ("stars", stars),
        ("forks", forks),
        ("followers", user.get("followers", 0)),
    ]

    body = '<text class="title" x="22" y="30">&gt; github stats</text>'
    positions = [(22, 68), (190, 68), (22, 126), (190, 126)]
    for (label, value), (x, y) in zip(rows, positions):
        body += f'<text class="value" x="{x}" y="{y}">{escape(fmt(value))}</text>'
        body += f'<text class="label" x="{x}" y="{y+19}">{escape(label)}</text>'

    body += f'<text class="label" x="22" y="174">public code: ~{escape(fmt(size_kb))} KB · generated by GitHub Actions</text>'
    return svg_shell(390, 195, body)


def build_languages(repos):
    totals = defaultdict(int)
    for repo in repos:
        try:
            langs = api(repo["languages_url"])
        except Exception:
            continue
        for lang, count in langs.items():
            totals[lang] += count

    top = sorted(totals.items(), key=lambda kv: kv[1], reverse=True)[:6]
    total = sum(v for _, v in top) or 1

    body = '<text class="title" x="22" y="30">&gt; top languages</text>'
    y = 58
    bar_x = 128
    bar_w = 225
    for lang, count in top:
        pct = count / total
        width = max(2, int(bar_w * pct))
        body += f'<text class="small" x="22" y="{y+10}">{escape(lang)}</text>'
        body += f'<rect x="{bar_x}" y="{y}" width="{bar_w}" height="10" rx="5" fill="#21262d"/>'
        body += f'<rect x="{bar_x}" y="{y}" width="{width}" height="10" rx="5" fill="#ff3030" opacity="{0.45 + pct * 0.55:.2f}"/>'
        body += f'<text class="label" x="360" y="{y+10}" text-anchor="end">{pct*100:.1f}%</text>'
        y += 23

    body += '<text class="label" x="22" y="190">calculated from non-fork public repositories</text>'
    return svg_shell(390, 210, body)


def main():
    user = api(f"https://api.github.com/users/{USERNAME}")
    repos = get_repos()
    (OUT / "stats.svg").write_text(build_stats(user, repos), encoding="utf-8")
    (OUT / "languages.svg").write_text(build_languages(repos), encoding="utf-8")
    print(f"generated stats for {USERNAME}: {len(repos)} repos")


if __name__ == "__main__":
    main()
